FROM node:16-alpine
RUN apk add wget
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" --  \
  -t robbyrussell \
  -p https://github.com/zsh-users/zsh-completions
WORKDIR /app
EXPOSE 3000
CMD [ "sh", "run.sh"]
