version: '3.8'
services:
  queue-provider:
    container_name: queue-provider
    build:
      context: ../
      dockerfile: Dockerfile.development
    volumes:
      - ../:/app
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - /var/run/docker.sock:/var/run/docker.sock
  localstack:
    image: localstack/localstack:latest
    container_name: queue-provider-localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - PERSISTENCE_SINGLE_FILE=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/localstack:/tmp/localstack
